/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#5e1800",
        "primary-fixed-dim": "#4fdbc8",
        "secondary-container": "#095252",
        "secondary-fixed": "#b0eeed",
        "on-error": "#690005",
        "surface": "#071325",
        "primary-container": "#14b8a6",
        "inverse-primary": "#006b5f",
        "background": "#071325",
        "on-tertiary-container": "#6c2106",
        "on-primary": "#003731",
        "on-surface": "#d7e3fc",
        "surface-container-lowest": "#030e20",
        "primary": "#4fdbc8",
        "error": "#ffb4ab",
        "primary-fixed": "#71f8e4",
        "error-container": "#93000a",
        "tertiary": "#ffb59e",
        "on-surface-variant": "#bbcac6",
        "surface-tint": "#4fdbc8",
        "on-primary-container": "#00423b",
        "on-tertiary-fixed-variant": "#7c2d11",
        "on-secondary-fixed": "#002020",
        "on-tertiary-fixed": "#3a0b00",
        "on-primary-fixed": "#00201c",
        "tertiary-fixed": "#ffdbd0",
        "surface-variant": "#2a3548",
        "inverse-on-surface": "#253144",
        "outline-variant": "#3c4947",
        "on-primary-fixed-variant": "#005048",
        "surface-dim": "#071325",
        "surface-container": "#142032",
        "surface-container-high": "#1f2a3d",
        "outline": "#859490",
        "inverse-surface": "#d7e3fc",
        "tertiary-container": "#f38764",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#94d1d1",
        "tertiary-fixed-dim": "#ffb59e",
        "secondary": "#94d1d1",
        "on-secondary": "#003737",
        "on-secondary-fixed-variant": "#044f4f",
        "surface-container-highest": "#2a3548",
        "surface-container-low": "#101c2e",
        "surface-bright": "#2e394d",
        "on-background": "#d7e3fc",
        "on-secondary-container": "#86c3c2"
      },
      fontFamily: {
        "headline": ["Manrope", "Noto Sans Bengali"],
        "body": ["Inter", "Noto Sans Bengali"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
