import { lazy, Suspense, useEffect, useMemo, useRef, useState } from "react";
import { motion } from "framer-motion";

const AmbientCells = lazy(() => import('../components/effects/AmbientCells'));
const AmbientCapsule = lazy(() => import('../components/effects/AmbientCapsule'));
import api, { validators } from "../services/api";
import { useAuth } from "../context/AuthContext";
import { ROLE_OPTIONS } from "../utils/auth";
import { isDemoDoctor, getMockDoctorPatientList, getMockDoctorHistory, getMockDoctorPendingReviews, getMockPrescriptions } from '../utils/mockData';
import CameraCapture from "../components/CameraCapture";
import ProcessingSteps from "../components/ProcessingSteps";
import ToastContainer, { useToasts } from "../components/ToastNotification";
import { AnimatedStatCard, LivePulseIndicator } from "../components/AnimatedStatCard";
import { DashboardHero3D } from "../components/DashboardHero3D";
import { pageTransition, dashboardStagger } from "../utils/animations";

/**
 * Generate a unique patient ID in format PID-XXXXXX
 * This is auto-generated by the system — doctors do not manually select patients.
 */
function generatePatientId() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let code = '';
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return `PID-${code}`;
}

/**
 * Handle copying text to clipboard with feedback
 */
const copyToClipboard = (text, callback) => {
  if (!text) return;
  navigator.clipboard.writeText(text).then(() => {
    if (callback) callback();
  });
};

function DoctorPanelPage() {
  const { user } = useAuth();
  const roleLabel = ROLE_OPTIONS.find((r) => r.value === user?.role)?.label || user?.role || 'User';
  const [analysisMode, setAnalysisMode] = useState("Simplified View");
  const [uploadStatus, setUploadStatus] = useState("Idle");
  const [uploadError, setUploadError] = useState("");
  const [uploadMessage, setUploadMessage] = useState("");
  const [selectedFile, setSelectedFile] = useState(null);
  const [extractionResult, setExtractionResult] = useState(null);
  const [isDropZoneActive, setIsDropZoneActive] = useState(false);
  const [reportType, setReportType] = useState('prescription');
  const fileInputRef = useRef(null);

  const [prescriptionHistory, setPrescriptionHistory] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  // Auto-generated patient ID (system-generated after diagnosis)
  const [autoPatientId, setAutoPatientId] = useState(null);
  const [dischargePatientId, setDischargePatientId] = useState(null);
  const [copiedId, setCopiedId] = useState(null);

  // Pending reviews from API
  const [pendingReviews, setPendingReviews] = useState([]);
  const [pendingLoading, setPendingLoading] = useState(true);
  const [exporting, setExporting] = useState(false);

  const [selectedReviewId, setSelectedReviewId] = useState(null);
  const [showCamera, setShowCamera] = useState(false);
  const { toasts, addToast, removeToast } = useToasts();

  // Patient selector state for existing/new patient mode
  const [patientMode, setPatientMode] = useState('new'); // 'new' | 'existing'
  const [patientList, setPatientList] = useState([]);
  const [patientsLoading, setPatientsLoading] = useState(false);
  const [selectedPatient, setSelectedPatient] = useState(null);
  const [patientSearch, setPatientSearch] = useState('');
  const [followUpHistory, setFollowUpHistory] = useState([]);
  const [followUpLoading, setFollowUpLoading] = useState(false);

  // Doctor identity from auth
  const doctorId = user?.user_id || user?.id || 'unknown-doctor';
  const doctorName = user?.name || 'Doctor';

  const selectedReview = pendingReviews.find((review) => review.id === selectedReviewId) ?? pendingReviews[0];

  // Fetch registered patients for the selector
  useEffect(() => {
    if (isDemoDoctor(user?.email)) {
      setPatientList(getMockDoctorPatientList());
      setPatientsLoading(false);
      return;
    }
    (async () => {
      setPatientsLoading(true);
      try {
        const result = await api.getPatients();
        setPatientList(result.items || []);
      } catch (err) {
        console.warn('Patient list fetch:', err.message);
      } finally {
        setPatientsLoading(false);
      }
    })();
  }, []);

  // Fetch follow-up history when an existing patient is selected
  const selectedPatientPid = selectedPatient?.pid || null;
  useEffect(() => {
    if (patientMode !== 'existing' || !selectedPatientPid) {
      setFollowUpHistory([]);
      return;
    }
    if (isDemoDoctor(user?.email)) {
      const demoRx = getMockPrescriptions().filter(rx => (rx.extracted_data?.patient_id || rx.patient_id) === selectedPatientPid);
      setFollowUpHistory(demoRx.sort((a, b) => new Date(b.created_at) - new Date(a.created_at)));
      setFollowUpLoading(false);
      return;
    }
    (async () => {
      setFollowUpLoading(true);
      try {
        const result = await api.getPatientPrescriptions(selectedPatientPid);
        setFollowUpHistory((result.items || []).sort((a, b) => new Date(b.created_at) - new Date(a.created_at)));
      } catch (err) {
        console.warn('Follow-up history fetch:', err.message);
      } finally {
        setFollowUpLoading(false);
      }
    })();
  }, [patientMode, selectedPatientPid]);

  // Filtered patient list for search
  const filteredPatients = patientList.filter(p => {
    const q = patientSearch.toLowerCase();
    return !q || (p.full_name || '').toLowerCase().includes(q) || (p.pid || '').toLowerCase().includes(q) || (p.email || '').toLowerCase().includes(q);
  });

  // Fetch pending prescriptions
  useEffect(() => {
    if (isDemoDoctor(user?.email)) {
      setPendingReviews(getMockDoctorPendingReviews());
      setPendingLoading(false);
      return;
    }
    (async () => {
      setPendingLoading(true);
      try {
        const result = await api.getPendingPrescriptions();
        if (result.items && result.items.length > 0) {
          setPendingReviews(result.items.map((item) => {
            const ed = item.extracted_data || item;
            return {
              id: item.prescription_id,
              patientId: ed.patient_id || 'Unknown',
              doctorId: item.doctor_id || 'Unknown',
              priority: (ed.extraction_confidence || 0) < 0.7 ? 'High' : 'Medium',
              summary: ed.diagnosis || 'Prescription pending review',
              submittedAt: item.created_at ? new Date(item.created_at).toLocaleString() : 'Recently',
            };
          }));
        }
      } catch (err) {
        console.warn('Pending prescriptions fetch:', err.message);
      } finally {
        setPendingLoading(false);
      }
    })();
  }, [uploadStatus]);

  // Fetch doctor's prescription history
  useEffect(() => {
    if (isDemoDoctor(user?.email)) {
      setPrescriptionHistory(getMockDoctorHistory());
      setHistoryLoading(false);
      return;
    }
    (async () => {
      setHistoryLoading(true);
      try {
        const result = await api.getDoctorPrescriptions(doctorId);
        setPrescriptionHistory(result.items || []);
      } catch (err) {
        console.warn('History fetch:', err.message);
      } finally {
        setHistoryLoading(false);
      }
    })();
  }, [doctorId, uploadStatus]);

  // Poll for new prescriptions every 30s (skip for demo accounts)
  useEffect(() => {
    if (isDemoDoctor(user?.email)) return;
    let prevCount = pendingReviews.length;
    const interval = setInterval(async () => {
      try {
        const result = await api.getPendingPrescriptions();
        const newCount = result.items?.length || 0;
        if (newCount > prevCount && prevCount > 0) {
          addToast(`${newCount - prevCount} new prescription(s) arrived!`, 'info');
        }
        prevCount = newCount;
      } catch { /* silent */ }
    }, 30000);
    return () => clearInterval(interval);
  }, []);

  // Compute dynamic stats
  const stats = useMemo(() => {
    const pending = pendingReviews.length;
    const approved = prescriptionHistory.filter((r) => (r.status || r.extracted_data?.status) === 'approved').length;
    return { pending, approved };
  }, [pendingReviews, prescriptionHistory]);

  const applySelectedFile = (file) => {
    if (!file) return;
    setSelectedFile(file);
    setUploadStatus("Idle");
    setUploadError("");
    setUploadMessage("");
  };

  const handleCameraCapture = (blob) => {
    const file = new File([blob], `scan_${Date.now()}.jpg`, { type: 'image/jpeg' });
    applySelectedFile(file);
    setShowCamera(false);
  };

  const handleSelectFile = (event) => {
    const file = event.target.files?.[0];
    applySelectedFile(file);
  };

  const handleFileDrop = (event) => {
    event.preventDefault();
    setIsDropZoneActive(false);
    const file = event.dataTransfer?.files?.[0];
    applySelectedFile(file);
  };

  const handleUploadPrescription = async () => {
    if (!selectedFile) {
      setUploadError("Please select a prescription file before uploading.");
      setUploadStatus("Failed");
      return;
    }

    try {
      validators.validateFile(selectedFile);
      setUploadStatus("Uploading");
      setUploadError("");
      setUploadMessage("");

      // Use existing patient PID or auto-generate a new one
      const systemPatientId = patientMode === 'existing' && selectedPatient?.pid
        ? selectedPatient.pid
        : generatePatientId();

      const response = await api.extractPrescription(selectedFile, doctorId, {
        reportType: reportType,
        patientId: systemPatientId,
      });

      setAutoPatientId(systemPatientId);
      setExtractionResult(response);
      setUploadStatus("Uploaded");
      setUploadMessage(
        `Extraction completed! Patient ID: ${systemPatientId} — auto-assigned and queued for review.`
      );
    } catch (error) {
      setUploadStatus("Failed");
      setUploadError(error.message || "Upload failed. Please try again.");
    }
  };

  const handleExportSummary = async () => {
    if (!doctorId) return;
    setExporting(true);
    try {
      const data = await api.getDailySummary(doctorId);
      if (!data.items || data.items.length === 0) {
        alert("No activity recorded for today yet.");
        return;
      }

      // Generate CSV
      const headers = ["Type", "Patient ID", "Description/Diagnosis", "Status", "Timestamp"];
      const rows = data.items.map(item => [
        item.type,
        item.pid,
        `"${item.diagnosis || item.name}"`, // Quote to handle commas
        item.status,
        item.timestamp
      ]);

      const csvContent = [
        headers.join(","),
        ...rows.map(r => r.join(","))
      ].join("\n");

      // Download
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.setAttribute("href", url);
      link.setAttribute("download", `SwasthaLink_Activity_${data.date}.csv`);
      link.style.visibility = "hidden";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      console.error("Export failed:", err);
      alert("Failed to export summary: " + err.message);
    } finally {
      setExporting(false);
    }
  };

  return (
    <motion.div className="p-4 sm:p-6 lg:p-10 relative z-10" {...pageTransition}>
      {/* 3D Hero Background */}
      <div className="absolute inset-0 h-64 pointer-events-none overflow-hidden -z-10">
        <DashboardHero3D variant="doctor" height="260px" />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#070e17]/60 to-[#070e17]" />
      </div>

      <Suspense fallback={null}>
        <AmbientCells className="hidden lg:block absolute right-4 bottom-32 w-44 h-44 opacity-25 z-0" />
      </Suspense>
      <Suspense fallback={null}>
        <AmbientCapsule className="hidden lg:block absolute left-4 bottom-64 w-40 h-40 opacity-20 z-0" />
      </Suspense>

      <ToastContainer toasts={toasts} removeToast={removeToast} />
      <header className="mb-8 lg:mb-10 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
        <motion.div
          className="space-y-3"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
        >
          <div className="flex items-center gap-3">
            <span className="text-primary font-bold tracking-[0.24em] uppercase text-xs">{roleLabel} Panel</span>
            <LivePulseIndicator status="active" label="Online" />
          </div>
          <h2 className="text-4xl lg:text-5xl font-headline font-extrabold tracking-tight text-white leading-tight">
            Clinical Review Command Desk
          </h2>
          <p className="text-sm text-teal-200">
            Signed in as: <span className="font-semibold text-white">{user?.name || "Doctor"}</span>
            {user?.systemId && (
              <span className="ml-2 text-[10px] font-mono text-cyan-300/70 bg-cyan-400/10 px-2 py-0.5 rounded border border-cyan-400/20">{user.systemId}</span>
            )}
          </p>
          <p className="text-slate-300 max-w-3xl">
            Upload prescriptions &amp; medical reports, track extraction results, and manage your patient communication pipeline.
          </p>
          <div className="pt-2">
            <button
              onClick={handleExportSummary}
              disabled={exporting}
              className="flex w-full sm:w-auto items-center justify-center gap-2 px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-teal-300 hover:bg-white/10 transition-all text-xs font-bold disabled:opacity-50"
            >
              <span className="material-symbols-outlined text-sm">{exporting ? "progress_activity" : "download_clinical_notes"}</span>
              {exporting ? "Preparing Report..." : "Export Daily Summary (CSV)"}
            </button>
          </div>
        </motion.div>

        <motion.div
          className="grid grid-cols-1 sm:grid-cols-3 gap-3 w-full lg:w-auto"
          {...dashboardStagger}
        >
          <AnimatedStatCard
            title="Pending"
            value={stats.pending}
            icon="hourglass_top"
            gradient="from-amber-400 to-orange-500"
            delay={0}
          />
          <AnimatedStatCard
            title="Approved"
            value={stats.approved}
            icon="check_circle"
            gradient="from-emerald-400 to-teal-500"
            delay={0.07}
          />
          <AnimatedStatCard
            title="Total"
            value={prescriptionHistory.length}
            icon="monitoring"
            gradient="from-cyan-400 to-blue-500"
            delay={0.14}
          />
        </motion.div>
      </header>

      <div className="grid grid-cols-12 gap-6 lg:gap-7">
        {/* Left Column — Pending Reviews */}
        <section className="col-span-12 lg:col-span-4 glass-card rounded-3xl border border-white/10 overflow-hidden">
          <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
            <div>
              <p className="text-sm font-bold text-white">Pending Reviews</p>
              <p className="text-xs text-slate-400">Prescriptions awaiting admin approval</p>
            </div>
            <span className="material-symbols-outlined text-teal-300">fact_check</span>
          </div>

          <div className="p-4 space-y-3 max-h-[560px] overflow-y-auto">
            {pendingReviews.length === 0 && !pendingLoading && (
              <div className="text-center py-8 text-slate-400 text-sm">
                <span className="material-symbols-outlined text-3xl block mb-2 text-slate-500">inbox</span>
                No pending prescriptions
              </div>
            )}
            {pendingReviews.map((review) => {
              const isSelected = selectedReviewId === review.id;
              return (
                <button
                  key={review.id}
                  onClick={() => setSelectedReviewId(review.id)}
                  className={`w-full text-left rounded-2xl p-4 border transition-all duration-300 ${
                    isSelected
                      ? "bg-teal-400/15 border-teal-300/40 shadow-[0_12px_30px_rgba(20,184,166,0.2)]"
                      : "bg-white/[0.03] border-white/10 hover:bg-white/[0.07]"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3 mb-2">
                    <div>
                      <p className="text-sm font-bold text-white">
                        {review.patientId}
                      </p>
                      <p className="text-[11px] text-slate-400">{review.id?.slice(0,8)}...</p>
                    </div>
                    <span
                      className={`text-[10px] px-2 py-1 rounded-full font-bold uppercase tracking-wider ${
                        review.priority === "High"
                          ? "bg-rose-500/20 text-rose-200"
                          : review.priority === "Medium"
                            ? "bg-amber-500/20 text-amber-200"
                            : "bg-cyan-500/20 text-cyan-200"
                      }`}
                    >
                      {review.priority}
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed">{review.summary}</p>
                  <div className="mt-3 flex items-center gap-2 text-[11px] text-slate-500">
                    <span className="material-symbols-outlined text-sm">schedule</span>
                    {review.submittedAt}
                  </div>
                </button>
              );
            })}
          </div>
        </section>

        {/* Middle Column — Discharge Summary (NEW) */}
        <section className="col-span-12 lg:col-span-8 flex flex-col gap-6">
          <div className="glass-card rounded-3xl border border-white/10 overflow-hidden">
            <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
              <div>
                <p className="text-sm font-bold text-white">Clinical Discharge Summary</p>
                <p className="text-xs text-slate-400">Process complex discharge notes to patient-friendly formats</p>
              </div>
              <span className="material-symbols-outlined text-teal-300">summarize</span>
            </div>
            
            <div className="p-5 space-y-4">
              {/* Auto-generated Patient ID + Target Role */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Patient ID</label>
                  <div className="rounded-2xl border border-white/10 bg-[#0d1f2d] px-3 py-3 flex items-center gap-3">
                    <span className="material-symbols-outlined text-teal-200">badge</span>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <p className="text-sm text-white font-mono font-bold tracking-wider">
                          {dischargePatientId || <span className="text-slate-400 italic font-normal font-sans">Wait for submit</span>}
                        </p>
                        {dischargePatientId && (
                          <button 
                            onClick={() => copyToClipboard(dischargePatientId, () => {
                              setCopiedId(dischargePatientId);
                              setTimeout(() => setCopiedId(null), 2000);
                            })}
                            className="text-teal-400 hover:text-white transition-colors"
                          >
                            <span className="material-symbols-outlined text-sm">
                              {copiedId === dischargePatientId ? 'check' : 'content_copy'}
                            </span>
                          </button>
                        )}
                      </div>
                      <p className="text-[10px] text-slate-500 uppercase tracking-tighter">System-generated clinical ID</p>
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Target Role</label>
                  <div className="rounded-2xl border border-white/10 bg-[#0d1f2d] px-3 py-2 flex items-center gap-3">
                    <span className="material-symbols-outlined text-cyan-200">manage_accounts</span>
                    <select
                      defaultValue="patient"
                      id="discharge-role-select"
                      className="w-full bg-transparent text-sm text-white outline-none"
                    >
                      <option value="patient" className="bg-[#0d1f2d] text-white">Patient</option>
                      <option value="caregiver" className="bg-[#0d1f2d] text-white">Caregiver</option>
                      <option value="elderly" className="bg-[#0d1f2d] text-white">Elderly Patient</option>
                    </select>
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Discharge Notes</label>
                <textarea
                  id="discharge-text-input"
                  rows="4"
                  className="w-full bg-[#0d1f2d] text-sm text-white border border-white/10 p-4 outline-none rounded-2xl resize-y focus:border-teal-400/50 transition-colors"
                  placeholder="Paste clinical discharge summary here (min 50 chars)..."
                ></textarea>
              </div>

              <button
                onClick={async () => {
                   const text = document.getElementById('discharge-text-input').value;
                   const role = document.getElementById('discharge-role-select').value;
                   if (text.length < 50) return alert("Text too short (min 50 chars)");

                   // Auto-generate a patient ID for this discharge
                   const newPatientId = generatePatientId();
                   setDischargePatientId(newPatientId);

                   setUploadStatus("Processing Discharge...");
                   try {
                     const response = await api.processSummary({
                       discharge_text: text,
                       role: role,
                       language: 'en',
                       patient_id: newPatientId,
                       doctor_id: doctorId
                     });
                     alert(`Discharge processed successfully! Patient ID: ${newPatientId}`);
                     setUploadStatus("Idle");
                   } catch(e) {
                     alert("Error processing: " + e.message);
                     setDischargePatientId(null);
                     setUploadStatus("Idle");
                   }
                }}
                className="w-full py-3 rounded-xl bg-gradient-to-r from-teal-300 to-cyan-400 text-[#06383a] font-bold hover:shadow-[0_12px_28px_rgba(20,184,166,0.35)] transition-all"
              >
                Simplify &amp; Save Discharge Summary
              </button>
            </div>
          </div>

          {/* Upload Configuration for Prescriptions */}
          <div className="glass-card rounded-3xl border border-white/10 overflow-hidden">
            <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
              <div>
                <p className="text-sm font-bold text-white">Upload Configuration</p>
                <p className="text-xs text-slate-400">Select patient, report type, and upload</p>
              </div>
              <span className="material-symbols-outlined text-cyan-300">assignment_ind</span>
            </div>

            <div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-5">
              {/* Patient Mode Toggle */}
              <div className="space-y-2 md:col-span-2">
                <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Patient Selection</label>
                <div className="flex flex-col sm:flex-row gap-2">
                  <button
                    onClick={() => { setPatientMode('new'); setSelectedPatient(null); }}
                    className={`flex-1 px-3 py-2.5 rounded-xl text-xs font-semibold border transition-all flex items-center justify-center gap-2 ${
                      patientMode === 'new'
                        ? "bg-teal-300/20 border-teal-300/40 text-teal-100 ring-1 ring-teal-300/30"
                        : "bg-white/[0.03] border-white/10 text-slate-300 hover:bg-white/[0.08]"
                    }`}
                  >
                    <span className="material-symbols-outlined text-sm">person_add</span>
                    New Patient (Auto-ID)
                  </button>
                  <button
                    onClick={() => setPatientMode('existing')}
                    className={`flex-1 px-3 py-2.5 rounded-xl text-xs font-semibold border transition-all flex items-center justify-center gap-2 ${
                      patientMode === 'existing'
                        ? "bg-cyan-300/20 border-cyan-300/40 text-cyan-100 ring-1 ring-cyan-300/30"
                        : "bg-white/[0.03] border-white/10 text-slate-300 hover:bg-white/[0.08]"
                    }`}
                  >
                    <span className="material-symbols-outlined text-sm">person_search</span>
                    Existing Patient
                  </button>
                </div>
              </div>

              {/* Existing Patient Selector */}
              {patientMode === 'existing' && (
                <div className="space-y-2 md:col-span-2">
                  <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Search &amp; Select Patient</label>
                  <input
                    type="text"
                    value={patientSearch}
                    onChange={(e) => setPatientSearch(e.target.value)}
                    placeholder="Search by name, PID, or email..."
                    className="w-full bg-[#0d1f2d] text-sm text-white border border-white/10 px-4 py-2.5 outline-none rounded-xl focus:border-cyan-400/50 transition-colors"
                  />
                  <div className="max-h-40 overflow-y-auto space-y-1 rounded-xl border border-white/10 bg-[#0b1a27] p-2">
                    {patientsLoading ? (
                      <p className="text-xs text-slate-400 text-center py-3">Loading patients...</p>
                    ) : filteredPatients.length === 0 ? (
                      <p className="text-xs text-slate-400 text-center py-3">No patients found</p>
                    ) : (
                      filteredPatients.map((p) => (
                        <button
                          key={p.user_id || p.pid}
                          onClick={() => setSelectedPatient(p)}
                          className={`w-full text-left rounded-lg px-3 py-2 text-xs transition-all flex items-center justify-between ${
                            selectedPatient?.pid === p.pid
                              ? "bg-cyan-400/15 border border-cyan-300/30 text-white"
                              : "hover:bg-white/[0.05] text-slate-300 border border-transparent"
                          }`}
                        >
                          <div>
                            <span className="font-semibold text-white">{p.full_name || 'Unknown'}</span>
                            <span className="ml-2 text-slate-400">{p.email || ''}</span>
                          </div>
                          {p.pid && <span className="font-mono text-cyan-300 text-[11px]">{p.pid}</span>}
                        </button>
                      ))
                    )}
                  </div>
                </div>
              )}

              {/* Patient ID Display */}
              <div className="space-y-2">
                <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Patient ID</label>
                <div className="rounded-2xl border border-white/10 bg-[#0d1f2d] px-3 py-3 flex items-center gap-3">
                  <span className="material-symbols-outlined text-teal-200">badge</span>
                  <div className="flex-1">
                    <div className="flex items-center justify-between">
                      <p className="text-sm text-white font-mono font-bold tracking-wider">
                        {patientMode === 'existing' && selectedPatient?.pid
                          ? selectedPatient.pid
                          : autoPatientId || <span className="text-slate-400 italic font-normal font-sans">Wait for upload</span>}
                      </p>
                      {(patientMode === 'existing' ? selectedPatient?.pid : autoPatientId) && (
                        <button 
                          onClick={() => copyToClipboard(patientMode === 'existing' ? selectedPatient.pid : autoPatientId, () => {
                            setCopiedId(patientMode === 'existing' ? selectedPatient.pid : autoPatientId);
                            setTimeout(() => setCopiedId(null), 2000);
                          })}
                          className="text-teal-400 hover:text-white transition-colors"
                        >
                          <span className="material-symbols-outlined text-sm">
                            {copiedId === (patientMode === 'existing' ? selectedPatient?.pid : autoPatientId) ? 'check' : 'content_copy'}
                          </span>
                        </button>
                      )}
                    </div>
                    <p className="text-[10px] text-slate-500 uppercase tracking-tighter">
                      {patientMode === 'existing' ? 'Linked patient record' : 'System-generated clinical ID'}
                    </p>
                  </div>
                </div>
              </div>

              {/* Doctor (from auth) */}
              <div className="space-y-2">
                <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Uploaded By</label>
                <div className="rounded-2xl border border-white/10 bg-[#0d1f2d] px-3 py-3 flex items-center gap-3">
                  <span className="material-symbols-outlined text-cyan-200">stethoscope</span>
                  <div>
                    <p className="text-sm text-white font-semibold">{doctorName}</p>
                    <p className="text-xs text-slate-400">{doctorId}</p>
                  </div>
                </div>
              </div>

              {/* Report Type */}
              <div className="space-y-2 md:col-span-2">
                <label className="text-[11px] uppercase tracking-[0.16em] text-slate-400">Report Type</label>
                <div className="flex flex-wrap gap-2">
                  {[
                    { value: 'prescription', label: '💊 Prescription' },
                    { value: 'ecg', label: '❤️ ECG' },
                    { value: 'echo', label: '🫀 Echo' },
                    { value: 'ct_scan', label: '🔍 CT Scan' },
                    { value: 'mri', label: '🧲 MRI' },
                    { value: 'blood_test', label: '🩸 Blood Test' },
                    { value: 'other', label: '📄 Other' },
                  ].map((type) => (
                    <button
                      key={type.value}
                      onClick={() => setReportType(type.value)}
                      className={`px-3 py-2 rounded-xl text-xs font-semibold border transition-all ${
                        reportType === type.value
                          ? "bg-teal-300/20 border-teal-300/40 text-teal-100 ring-1 ring-teal-300/30"
                          : "bg-white/[0.03] border-white/10 text-slate-300 hover:bg-white/[0.08]"
                      }`}
                    >
                      {type.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Follow-up History — shown when existing patient selected */}
          {patientMode === 'existing' && selectedPatient?.pid && (
            <div className="glass-card rounded-3xl border border-white/10 overflow-hidden">
              <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
                <div>
                  <p className="text-sm font-bold text-white">Follow-up History — {selectedPatient.full_name || selectedPatient.pid}</p>
                  <p className="text-xs text-slate-400">Previous prescriptions and visits for this patient</p>
                </div>
                <span className="material-symbols-outlined text-amber-300">history</span>
              </div>
              <div className="p-4 max-h-72 overflow-y-auto">
                {followUpLoading ? (
                  <p className="text-xs text-slate-400 text-center py-6">Loading history...</p>
                ) : followUpHistory.length === 0 ? (
                  <div className="text-center py-6 text-slate-400 text-sm">
                    <span className="material-symbols-outlined text-2xl block mb-2 text-slate-500">history_toggle_off</span>
                    No previous records for this patient
                  </div>
                ) : (
                  <div className="space-y-2">
                    {followUpHistory.map((rx, i) => {
                      const ed = rx.extracted_data || {};
                      const date = rx.created_at ? new Date(rx.created_at) : null;
                      return (
                        <div key={rx.prescription_id || i} className="rounded-xl bg-white/[0.03] border border-white/10 px-4 py-3">
                          <div className="flex items-center justify-between mb-1">
                            <div className="flex items-center gap-2">
                              <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${
                                rx.status === 'approved' ? 'bg-emerald-500/20 text-emerald-200'
                                : rx.status === 'pending_admin_review' ? 'bg-amber-500/20 text-amber-200'
                                : 'bg-slate-500/20 text-slate-300'
                              }`}>{rx.status === 'pending_admin_review' ? 'Pending' : rx.status || 'N/A'}</span>
                              <span className="text-[10px] text-slate-500">{rx.report_type || 'prescription'}</span>
                            </div>
                            {date && (
                              <span className="text-[10px] text-slate-500">
                                {date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} {date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}
                              </span>
                            )}
                          </div>
                          <p className="text-xs text-white font-semibold">{ed.diagnosis || 'No diagnosis recorded'}</p>
                          {ed.medications?.length > 0 && (
                            <p className="text-[11px] text-slate-400 mt-1">
                              Medications: {ed.medications.map(m => m.name).filter(Boolean).join(', ') || `${ed.medications.length} item(s)`}
                            </p>
                          )}
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Upload + Extraction Result */}
          <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
            {/* Document Upload */}
            <div className="glass-card rounded-3xl border border-white/10 overflow-hidden">
              <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
                <div>
                  <p className="text-sm font-bold text-white">Document Upload</p>
                  <p className="text-xs text-slate-400">Upload prescription or medical report</p>
                </div>
                <span className="material-symbols-outlined text-cyan-300">upload_file</span>
              </div>
              <div className="p-5 space-y-4">
                <div className="rounded-xl bg-white/[0.03] border border-white/10 px-4 py-3 text-xs text-slate-300 flex flex-wrap items-center gap-2">
                  <span className="font-semibold text-white">Patient ID:</span> {patientMode === 'existing' && selectedPatient?.pid ? <span className="text-cyan-200 font-mono">{selectedPatient.pid}</span> : autoPatientId || <span className="italic text-slate-400">Will be auto-assigned</span>}
                  <span className="w-1 h-1 rounded-full bg-slate-600"></span>
                  <span className="font-semibold text-white">Type:</span> {reportType}
                </div>
                <div
                  onDragOver={(e) => { e.preventDefault(); setIsDropZoneActive(true); }}
                  onDragLeave={() => setIsDropZoneActive(false)}
                  onDrop={handleFileDrop}
                  className={`rounded-2xl border-2 border-dashed p-6 text-center transition-all ${
                    isDropZoneActive
                      ? "border-teal-200 bg-teal-400/15 shadow-[0_0_20px_rgba(45,212,191,0.25)]"
                      : "border-teal-300/40 bg-teal-400/5"
                  }`}
                >
                  <span className="material-symbols-outlined text-4xl text-teal-200">cloud_upload</span>
                  <p className="text-sm text-slate-100 mt-2">Drag and drop file here</p>
                  <p className="text-xs text-slate-400 mt-1">Supports JPG, PNG, PDF up to 10MB</p>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/png,image/jpeg"
                    onChange={handleSelectFile}
                    className="hidden"
                  />
                  <div className="mt-4 flex items-center justify-center gap-3">
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      className="px-4 py-2 rounded-xl bg-white/10 border border-white/15 text-xs text-white font-semibold hover:bg-white/15 transition-all"
                    >
                      Choose File
                    </button>
                    <button
                      type="button"
                      onClick={() => setShowCamera(true)}
                      className="px-4 py-2 rounded-xl bg-teal-400/15 border border-teal-300/30 text-xs text-teal-200 font-semibold hover:bg-teal-400/25 transition-all flex items-center gap-1.5"
                    >
                      <span className="material-symbols-outlined text-sm">photo_camera</span>
                      Scan Document
                    </button>
                  </div>
                  {selectedFile && (
                    <p className="text-xs text-teal-200 mt-3 break-all">Selected: {selectedFile.name}</p>
                  )}
                </div>
                <button
                  onClick={handleUploadPrescription}
                  disabled={uploadStatus === "Uploading"}
                  className="w-full py-3 rounded-xl bg-gradient-to-r from-teal-300 to-cyan-400 text-[#06383a] font-bold hover:shadow-[0_12px_28px_rgba(20,184,166,0.35)] transition-all disabled:opacity-60 disabled:cursor-not-allowed"
                >
                  {uploadStatus === "Uploading" ? "Extracting Document..." : "Upload & Extract"}
                </button>
                <div className="rounded-xl bg-white/[0.03] border border-white/10 px-4 py-3 flex items-center justify-between">
                  <span className="text-xs text-slate-300">Upload status</span>
                  <span className={`text-xs font-bold px-2 py-1 rounded-full ${
                    uploadStatus === "Uploaded" ? "bg-emerald-500/20 text-emerald-200"
                    : uploadStatus === "Uploading" ? "bg-amber-500/20 text-amber-200"
                    : uploadStatus === "Failed" ? "bg-rose-500/20 text-rose-200"
                    : "bg-slate-500/20 text-slate-200"
                  }`}>
                    {uploadStatus}
                  </span>
                </div>
                <ProcessingSteps isActive={uploadStatus === "Uploading" || uploadStatus === "Processing Discharge..."} />
                {uploadMessage && (
                  <div className="rounded-xl bg-emerald-500/10 border border-emerald-300/30 px-4 py-3 text-xs text-emerald-100">
                    {uploadMessage}
                  </div>
                )}
                {uploadError && (
                  <div className="rounded-xl bg-rose-500/10 border border-rose-300/30 px-4 py-3 text-xs text-rose-100">
                    {uploadError}
                  </div>
                )}
              </div>
            </div>

            {/* Extraction Result */}
            <div className="glass-card rounded-3xl border border-white/10 overflow-hidden">
              <div className="px-5 py-4 border-b border-white/10 bg-white/[0.03] flex items-center justify-between">
                <div>
                  <p className="text-sm font-bold text-white">Extraction Result</p>
                  <p className="text-xs text-slate-400">AI-extracted structured data</p>
                </div>
                <span className="material-symbols-outlined text-teal-300">auto_awesome</span>
              </div>
              <div className="p-5 space-y-3">
                {extractionResult?.extracted_data ? (
                  <>
                    <div className="flex items-center justify-between mb-3">
                      <span className="text-[10px] uppercase tracking-wider bg-emerald-500/20 text-emerald-200 px-2 py-1 rounded-full">Live Extraction</span>
                      <span className="text-[10px] text-slate-400">Confidence: {Math.round((extractionResult.extracted_data.extraction_confidence || 0) * 100)}%</span>
                    </div>
                    <div className="space-y-2 text-xs">
                      <p className="text-slate-300"><span className="text-white font-semibold">Rx ID:</span> {extractionResult.prescription_id?.slice(0,8)}...</p>
                      <p className="text-slate-300">
                        <span className="text-white font-semibold">Patient ID:</span>{' '}
                        <span className="text-teal-200 font-mono font-bold">{autoPatientId || 'N/A'}</span>
                      </p>
                      <p className="text-slate-300"><span className="text-white font-semibold">Patient Name:</span> {extractionResult.extracted_data.patient_name || "Extracted from document"}</p>
                      <p className="text-slate-300"><span className="text-white font-semibold">Doctor:</span> {extractionResult.extracted_data.doctor_name || doctorName}</p>
                      <p className="text-slate-300"><span className="text-white font-semibold">Diagnosis:</span> {extractionResult.extracted_data.diagnosis || "Not specified"}</p>
                      <p className="text-slate-300"><span className="text-white font-semibold">Medications:</span> {extractionResult.extracted_data.medications?.length || 0}</p>
                      {extractionResult.extracted_data.tests?.length > 0 && (
                        <p className="text-slate-300"><span className="text-white font-semibold">Tests:</span> {extractionResult.extracted_data.tests.length}</p>
                      )}
                    </div>
                    {/* Medications list */}
                    {extractionResult.extracted_data.medications?.length > 0 && (
                      <div className="mt-3 space-y-2">
                        <p className="text-[10px] uppercase tracking-wider text-slate-400">Medications</p>
                        {extractionResult.extracted_data.medications.map((med, i) => (
                          <div key={i} className="rounded-xl bg-white/[0.03] border border-white/10 px-3 py-2 text-xs">
                            <p className="font-semibold text-white">{med.name} {med.strength || ''}</p>
                            <p className="text-slate-400">{[med.form, med.frequency, med.duration, med.instructions].filter(Boolean).join(' • ')}</p>
                            {med.purpose && <p className="text-teal-200 mt-1">{med.purpose}</p>}
                          </div>
                        ))}
                      </div>
                    )}
                  </>
                ) : (
                  <div className="text-center py-10 text-slate-400 text-sm">
                    <span className="material-symbols-outlined text-4xl block mb-2 text-slate-500">biotech</span>
                    Upload a document to see extraction results
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>
      </div>

      {showCamera && (
        <CameraCapture
          onCapture={handleCameraCapture}
          onClose={() => setShowCamera(false)}
        />
      )}
    </motion.div>
  );
}

export default DoctorPanelPage;
