apiVersion: v1
kind: Service
metadata:
  name: swasthalink-backend
  namespace: swasthalink
spec:
  selector:
    app: swasthalink-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
