apiVersion: apps/v1
kind: Deployment
metadata:
  name: swasthalink-backend
  namespace: swasthalink
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: swasthalink-backend
  template:
    metadata:
      labels:
        app: swasthalink-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/suvam-paul145/swasthalink-backend:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
